### ISSUE TITLE
Settings page title is 'Your Bookings'

### ISSUE THREAD

**Issue by tashinam** [asekeyboardwarriors/killer-app#22]
The page title of Settings displays as 'Your Bookings' instead of 'Settings'.

<img width="355" alt="Screenshot 2019-11-14 at 12 40 40" src="https://user-images.githubusercontent.com/43495234/68858470-05056480-06dd-11ea-9ce6-8f74ed8348d5.png">

**Comment by HarryPi** [comment]
This is simple give it a go @tashinam

**Comment by DominikWas** [comment]
Fixed in bb72294ce2e3d57a0d643f83fc07c0559c059a27
