### ISSUE TITLE
Save function not working

### ISSUE THREAD

**Issue by tashinam** [asekeyboardwarriors/killer-app#24]
Pressing the save icon comes up with the message 'Failed to save new settings'

Closing the app and reopening with the same login details shows that it indeed has not saved.

<img width="373" alt="Screenshot 2019-11-14 at 12 57 56" src="https://user-images.githubusercontent.com/43495234/68859105-7d205a00-06de-11ea-9b0c-8091042f3417.png">

**Comment by HarryPi** [comment]
Relate to https://github.com/asekeyboardwarriors/killer-app/issues/26.

**Comment by HarryPi** [comment]
Closed in https://github.com/asekeyboardwarriors/killer-app/commit/38bbd3b9628bf214477cf050dfe19d0480da6c84
