### ISSUE TITLE
'Failed to create user settings'

### ISSUE THREAD

**Issue by tashinam** [asekeyboardwarriors/killer-app#26]
Error message 'Failed to create user settings' appears when logging in again with the same user after rebooting the app.

<img width="365" alt="Screenshot 2019-11-14 at 13 09 28" src="https://user-images.githubusercontent.com/43495234/68859896-39c6eb00-06e0-11ea-9cf7-217dbc65a0b2.png">

**Comment by HarryPi** [comment]
Is this with the browser or the mobile app running?

**Comment by tashinam** [comment]
Not sure I understand your question. It's the ios emulator using ionic capacitor. Do I need to connect to Heroku myself before running the emulator?

**Comment by HarryPi** [comment]
No no thats fine because you can run the app on either web using mob view or emulator wanted to know where did you run it. Will investigate, please add the error message from Xcode as well if possible

**Comment by tashinam** [comment]
ERROR MESSAGE:  {"message":"The file “user_settings.json” doesn’t exist.","errorMessage":"The file “user_settings.json” doesn’t exist."}

**Comment by HarryPi** [comment]
This appears to be a permission issue. Will fix and update when done

**Comment by HarryPi** [comment]
Further investigation reveals that this happens as the app attempts to write to the file before permissions are granted

**Comment by HarryPi** [comment]
Fixed in https://github.com/asekeyboardwarriors/killer-app/commit/38bbd3b9628bf214477cf050dfe19d0480da6c84
